### Test Tuition Debtors Report API
GET http://localhost:5264/pagos/tuition-debtors-report
Content-Type: application/json

### Test with filters
GET http://localhost:5264/pagos/tuition-debtors-report?sedeId=1&gradoId=1&limit=10
Content-Type: application/json

### Test with different date
GET http://localhost:5264/pagos/tuition-debtors-report?reportDate=2025-01-11
Content-Type: application/json
