### Test Transport Debtors Report API - Basic
GET http://localhost:5264/pagos/transport-debtors-report
Content-Type: application/json

### Test with filters
GET http://localhost:5264/pagos/transport-debtors-report?year=2025&month=1&sedeId=1
Content-Type: application/json

### Test with specific rubro (transport route)
GET http://localhost:5264/pagos/transport-debtors-report?year=2025&rubroId=1
Content-Type: application/json

### Test with specific grado
GET http://localhost:5264/pagos/transport-debtors-report?year=2025&gradoId=1
Content-Type: application/json
