// <auto-generated />
using System;
using ManitasCreativas.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ManitasCreativas.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250726000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BecaParcialPorcentaje")
                        .HasColumnType("numeric");

                    b.Property<bool?>("Becado")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("GradoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Seccion")
                        .HasColumnType("text");

                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("text");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text");

                    b.Property<string>("TercerNombre")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GradoId");

                    b.HasIndex("SedeId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.AlumnoContacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int>("ContactoId")
                        .HasColumnType("integer");

                    b.Property<string>("Parentesco")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("ContactoId");

                    b.ToTable("AlumnoContactos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.AlumnoRuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RubroTransporteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("RubroTransporteId");

                    b.ToTable("AlumnoRutas");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.CodigosQRPagos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoQR")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PagoId")
                        .IsUnique();

                    b.ToTable("CodigosQRPagos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroTelefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.EntradaUniforme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FechaEntrada")
                        .HasDatabaseName("IX_EntradaUniforme_FechaEntrada");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("EntradaUniformes");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.EntradaUniformeDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("EntradaUniformeId")
                        .HasColumnType("integer");

                    b.Property<int>("PrendaUniformeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EntradaUniformeId");

                    b.HasIndex("PrendaUniformeId");

                    b.ToTable("EntradaUniformeDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("NivelEducativoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NivelEducativoId");

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.NivelEducativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NivelesEducativos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<bool>("Anulado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("MotivoAnulacion")
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("RubroId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PagoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("RubroUniformeDetalleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PagoId");

                    b.HasIndex("RubroUniformeDetalleId");

                    b.ToTable("PagoDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PagoImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsImagenEliminada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Tamano")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PagoId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("PagoImagenes");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PrendaUniforme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Sexo")
                        .HasDatabaseName("IX_PrendaUniforme_Sexo");

                    b.HasIndex("Talla")
                        .HasDatabaseName("IX_PrendaUniforme_Talla");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("PrendasUniforme");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PrendaUniformeImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrendaUniformeId")
                        .HasColumnType("integer");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Tamano")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrendaUniformeId");

                    b.ToTable("PrendaUniformeImagenes");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsAdmin = true,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            EsAdmin = false,
                            Nombre = "Usuario"
                        });
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EsCarnet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsPagoDeUniforme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsTransporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("MontoPreestablecido")
                        .HasColumnType("numeric");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrdenVisualizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.RubroUniformeDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsEliminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PrendaUniformeId")
                        .HasColumnType("integer");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrendaUniformeId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("RubroId", "PrendaUniformeId")
                        .IsUnique()
                        .HasDatabaseName("IX_RubroUniformeDetalle_RubroId_PrendaUniformeId");

                    b.ToTable("RubroUniformeDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Sede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Alumno", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Grado", "Grado")
                        .WithMany("Alumnos")
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Sede", "Sede")
                        .WithMany("Alumnos")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grado");

                    b.Navigation("Sede");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.AlumnoContacto", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Alumno", "Alumno")
                        .WithMany("AlumnoContactos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Contacto", "Contacto")
                        .WithMany("AlumnoContactos")
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.AlumnoRuta", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Rubro", "RubroTransporte")
                        .WithMany()
                        .HasForeignKey("RubroTransporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("RubroTransporte");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.CodigosQRPagos", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Pago", "Pago")
                        .WithOne("CodigoQR")
                        .HasForeignKey("ManitasCreativas.Domain.Entities.CodigosQRPagos", "PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.EntradaUniforme", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.EntradaUniformeDetalle", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.EntradaUniforme", "EntradaUniforme")
                        .WithMany("EntradaUniformeDetalles")
                        .HasForeignKey("EntradaUniformeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.PrendaUniforme", "PrendaUniforme")
                        .WithMany("EntradaUniformeDetalles")
                        .HasForeignKey("PrendaUniformeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntradaUniforme");

                    b.Navigation("PrendaUniforme");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Grado", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.NivelEducativo", "NivelEducativo")
                        .WithMany("Grados")
                        .HasForeignKey("NivelEducativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelEducativo");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Pago", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Alumno", "Alumno")
                        .WithMany("Pagos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Rubro", "Rubro")
                        .WithMany("Pagos")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Rubro");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PagoDetalle", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Pago", "Pago")
                        .WithMany("PagoDetalles")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.RubroUniformeDetalle", "RubroUniformeDetalle")
                        .WithMany("PagoDetalles")
                        .HasForeignKey("RubroUniformeDetalleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Pago");

                    b.Navigation("RubroUniformeDetalle");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PagoImagen", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Pago", "Pago")
                        .WithMany("PagoImagenes")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pago");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PrendaUniforme", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PrendaUniformeImagen", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.PrendaUniforme", "PrendaUniforme")
                        .WithMany("ImagenesPrenda")
                        .HasForeignKey("PrendaUniformeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrendaUniforme");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Rubro", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.RubroUniformeDetalle", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.PrendaUniforme", "PrendaUniforme")
                        .WithMany("RubroUniformeDetalles")
                        .HasForeignKey("PrendaUniformeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Rubro", "Rubro")
                        .WithMany("RubroUniformeDetalles")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PrendaUniforme");

                    b.Navigation("Rubro");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Alumno", b =>
                {
                    b.Navigation("AlumnoContactos");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Contacto", b =>
                {
                    b.Navigation("AlumnoContactos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.EntradaUniforme", b =>
                {
                    b.Navigation("EntradaUniformeDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Grado", b =>
                {
                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.NivelEducativo", b =>
                {
                    b.Navigation("Grados");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Pago", b =>
                {
                    b.Navigation("CodigoQR");

                    b.Navigation("PagoDetalles");

                    b.Navigation("PagoImagenes");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PrendaUniforme", b =>
                {
                    b.Navigation("EntradaUniformeDetalles");

                    b.Navigation("ImagenesPrenda");

                    b.Navigation("RubroUniformeDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Rubro", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("RubroUniformeDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.RubroUniformeDetalle", b =>
                {
                    b.Navigation("PagoDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Sede", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
