// <auto-generated />
using System;
using ManitasCreativas.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ManitasCreativas.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250901181350_AddFechaTrasladoToAlumno")]
    partial class AddFechaTrasladoToAlumno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BecaParcialPorcentaje")
                        .HasColumnType("numeric");

                    b.Property<bool?>("Becado")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaTraslado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GradoId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Seccion")
                        .HasColumnType("text");

                    b.Property<int>("SedeId")
                        .HasColumnType("integer");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("text");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text");

                    b.Property<string>("TercerNombre")
                        .HasColumnType("text");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GradoId");

                    b.HasIndex("SedeId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Alumnos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.AlumnoContacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int>("ContactoId")
                        .HasColumnType("integer");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("ContactoId");

                    b.ToTable("AlumnoContactos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.AlumnoRuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RubroTransporteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("RubroTransporteId");

                    b.ToTable("AlumnoRutas");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.CodigosQRPagos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstaUsado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TokenUnico")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PagoId")
                        .IsUnique();

                    b.ToTable("CodigosQRPagos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nit")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoTrabajo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.EntradaUniforme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoEliminacion")
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FechaEntrada")
                        .HasDatabaseName("IX_EntradaUniforme_FechaEntrada");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioEliminacionId");

                    b.ToTable("EntradaUniformes");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.EntradaUniformeDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("EntradaUniformeId")
                        .HasColumnType("integer");

                    b.Property<int>("PrendaUniformeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EntradaUniformeId");

                    b.HasIndex("PrendaUniformeId");

                    b.ToTable("EntradaUniformeDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NivelEducativoId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NivelEducativoId");

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.NivelEducativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NivelesEducativos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer");

                    b.Property<int?>("AnioColegiatura")
                        .HasColumnType("integer");

                    b.Property<int>("CicloEscolar")
                        .HasColumnType("integer");

                    b.Property<bool>("EsAnulado")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsColegiatura")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EsPagoDeCarnet")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EsPagoDeTransporte")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EsPagoDeUniforme")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoCarnet")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MedioPago")
                        .HasColumnType("integer");

                    b.Property<int?>("MesColegiatura")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<string>("MotivoAnulacion")
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioAnulacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("RubroId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioAnulacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PagoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("RubroUniformeDetalleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PagoId");

                    b.HasIndex("RubroUniformeDetalleId");

                    b.ToTable("PagoDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PagoImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("EsImagenEliminada")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PagoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PagoId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("PagoImagenes");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PrendaUniforme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Entradas")
                        .HasColumnType("integer");

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("boolean");

                    b.Property<int>("ExistenciaInicial")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoEliminacion")
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Salidas")
                        .HasColumnType("integer");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Sexo")
                        .HasDatabaseName("IX_PrendaUniforme_Sexo");

                    b.HasIndex("Talla")
                        .HasDatabaseName("IX_PrendaUniforme_Talla");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioEliminacionId");

                    b.ToTable("PrendasUniforme");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PrendaUniformeImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrendaUniformeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrendaUniformeId");

                    b.ToTable("PrendaUniformeImagenes");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EsAdmin = true,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            EsAdmin = false,
                            Nombre = "Usuario"
                        },
                        new
                        {
                            Id = 3,
                            EsAdmin = false,
                            Nombre = "Secretaria"
                        },
                        new
                        {
                            Id = 4,
                            EsAdmin = false,
                            Nombre = "Contador"
                        });
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Rubro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int?>("CicloEscolar")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DiaLimitePagoAmarillo")
                        .HasColumnType("integer");

                    b.Property<int?>("DiaLimitePagoRojo")
                        .HasColumnType("integer");

                    b.Property<bool>("EsColegiatura")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EsPagoDeCarnet")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EsPagoDeTransporte")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EsPagoDeUniforme")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaFinPromocion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicioPromocion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLimitePagoAmarillo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaLimitePagoRojo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GradoId")
                        .HasColumnType("integer");

                    b.Property<int?>("MesLimitePago")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MontoPreestablecido")
                        .HasColumnType("numeric");

                    b.Property<int?>("NivelEducativoId")
                        .HasColumnType("integer");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int?>("OrdenVisualizacionGrid")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PenalizacionPorMoraMonto")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PenalizacionPorMoraPorcentaje")
                        .HasColumnType("numeric");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GradoId");

                    b.HasIndex("NivelEducativoId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.RubroUniformeDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsEliminado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoEliminacion")
                        .HasColumnType("text");

                    b.Property<int>("PrendaUniformeId")
                        .HasColumnType("integer");

                    b.Property<int>("RubroId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioActualizacionId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioEliminacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PrendaUniformeId");

                    b.HasIndex("UsuarioActualizacionId");

                    b.HasIndex("UsuarioCreacionId");

                    b.HasIndex("UsuarioEliminacionId");

                    b.HasIndex("RubroId", "PrendaUniformeId")
                        .IsUnique()
                        .HasDatabaseName("IX_RubroUniformeDetalle_RubroId_PrendaUniformeId");

                    b.ToTable("RubroUniformeDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Sede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstadoUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetExpires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Alumno", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Grado", "Grado")
                        .WithMany()
                        .HasForeignKey("GradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Sede", "Sede")
                        .WithMany("Alumnos")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grado");

                    b.Navigation("Sede");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.AlumnoContacto", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Alumno", "Alumno")
                        .WithMany("AlumnoContactos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Contacto", "Contacto")
                        .WithMany("AlumnosContacto")
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.AlumnoRuta", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Alumno", "Alumno")
                        .WithMany()
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Rubro", "RubroTransporte")
                        .WithMany()
                        .HasForeignKey("RubroTransporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("RubroTransporte");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.CodigosQRPagos", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Pago", "Pago")
                        .WithOne("CodigoQR")
                        .HasForeignKey("ManitasCreativas.Domain.Entities.CodigosQRPagos", "PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.EntradaUniforme", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioEliminacion")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminacionId");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioEliminacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.EntradaUniformeDetalle", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.EntradaUniforme", "EntradaUniforme")
                        .WithMany("EntradaUniformeDetalles")
                        .HasForeignKey("EntradaUniformeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.PrendaUniforme", "PrendaUniforme")
                        .WithMany("EntradaUniformeDetalles")
                        .HasForeignKey("PrendaUniformeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntradaUniforme");

                    b.Navigation("PrendaUniforme");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Grado", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.NivelEducativo", "NivelEducativo")
                        .WithMany("Grados")
                        .HasForeignKey("NivelEducativoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelEducativo");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Pago", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Alumno", "Alumno")
                        .WithMany("Pagos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Rubro", "Rubro")
                        .WithMany("Pagos")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioAnulacion")
                        .WithMany()
                        .HasForeignKey("UsuarioAnulacionId");

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Rubro");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioAnulacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PagoDetalle", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Pago", "Pago")
                        .WithMany("PagoDetalles")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.RubroUniformeDetalle", "RubroUniformeDetalle")
                        .WithMany("PagoDetalles")
                        .HasForeignKey("RubroUniformeDetalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pago");

                    b.Navigation("RubroUniformeDetalle");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PagoImagen", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Pago", "Pago")
                        .WithMany("ImagenesPago")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId");

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PrendaUniforme", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioEliminacion")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminacionId");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioEliminacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PrendaUniformeImagen", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.PrendaUniforme", "PrendaUniforme")
                        .WithMany("ImagenesPrenda")
                        .HasForeignKey("PrendaUniformeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrendaUniforme");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Rubro", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Grado", "Grado")
                        .WithMany("Rubros")
                        .HasForeignKey("GradoId");

                    b.HasOne("ManitasCreativas.Domain.Entities.NivelEducativo", "NivelEducativo")
                        .WithMany()
                        .HasForeignKey("NivelEducativoId");

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId");

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grado");

                    b.Navigation("NivelEducativo");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.RubroUniformeDetalle", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.PrendaUniforme", "PrendaUniforme")
                        .WithMany("RubroUniformeDetalles")
                        .HasForeignKey("PrendaUniformeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Rubro", "Rubro")
                        .WithMany("RubroUniformeDetalles")
                        .HasForeignKey("RubroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioCreacion")
                        .WithMany()
                        .HasForeignKey("UsuarioCreacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ManitasCreativas.Domain.Entities.Usuario", "UsuarioEliminacion")
                        .WithMany()
                        .HasForeignKey("UsuarioEliminacionId");

                    b.Navigation("PrendaUniforme");

                    b.Navigation("Rubro");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioCreacion");

                    b.Navigation("UsuarioEliminacion");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ManitasCreativas.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Alumno", b =>
                {
                    b.Navigation("AlumnoContactos");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Contacto", b =>
                {
                    b.Navigation("AlumnosContacto");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.EntradaUniforme", b =>
                {
                    b.Navigation("EntradaUniformeDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Grado", b =>
                {
                    b.Navigation("Rubros");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.NivelEducativo", b =>
                {
                    b.Navigation("Grados");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Pago", b =>
                {
                    b.Navigation("CodigoQR");

                    b.Navigation("ImagenesPago");

                    b.Navigation("PagoDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.PrendaUniforme", b =>
                {
                    b.Navigation("EntradaUniformeDetalles");

                    b.Navigation("ImagenesPrenda");

                    b.Navigation("RubroUniformeDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Rubro", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("RubroUniformeDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.RubroUniformeDetalle", b =>
                {
                    b.Navigation("PagoDetalles");
                });

            modelBuilder.Entity("ManitasCreativas.Domain.Entities.Sede", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
